// <auto-generated />
using System;
using CRM.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRM.Infra.Migrations
{
    [DbContext(typeof(ContextDb))]
    [Migration("20250719204442_Lead")]
    partial class Lead
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CRM.Domain.Entities.Lead", b =>
                {
                    b.Property<int>("leadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("leadId"));

                    b.Property<string>("bairro")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("cep")
                        .HasMaxLength(9)
                        .HasColumnType("varchar(9)");

                    b.Property<string>("cidade")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("codigoBarrasBoleto")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("complemento")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("dataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dataPagamento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dataUltimaAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dataVencimentoBoleto")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("endereco")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("estado")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("formaPagto")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("link")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("linkBarCode")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("linkPdf")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("linkQRCode")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("nomeArquivo")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("nomeContato")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("numero")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<bool?>("pgto")
                        .HasColumnType("bit");

                    b.Property<string>("status")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("statusCadastro")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("telefone1")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("telefone2")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("token")
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.Property<string>("urlArquivo")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.HasKey("leadId");

                    b.ToTable("Lead");
                });

            modelBuilder.Entity("CRM.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("sobrenome")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
